# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.17.0
    hooks:
      - id: eslint
        files: \.([jt]sx?|vue)$ # *.js, *.jsx, *.ts, *.tsx and *.vue
        types: [file]
        additional_dependencies:
          - eslint@8.17.0
          - typescript@4.7.3
          - '@typescript-eslint/eslint-plugin@5.28.0'
          - '@typescript-eslint/parser@5.28.0'
          - eslint-config-prettier@8.5.0
          - eslint-plugin-jest@26.5.3
          - eslint-plugin-vue@9.1.1
          - vue-eslint-parser@9.0.2
          - jest@27.4.7
