# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        files: \.([jt]sx?|vue)$ # *.js, *.jsx, *.ts, *.tsx and *.vue
        types: [file]
        additional_dependencies:
          - eslint@7.32.0
          - typescript@4.4.3
          - '@typescript-eslint/eslint-plugin@4.31.1'
          - '@typescript-eslint/parser@4.31.1'
          - eslint-plugin-vue@7.18.0
          - vue-eslint-parser@7.11.0
          - jest@27.2.0
          - eslint-plugin-jest@24.4.2
          - eslint-config-prettier@8.3.0
